// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using game_tools.Helpers;

#nullable disable

namespace game_tools.Migrations
{
    [DbContext(typeof(SQLiteDb))]
    partial class SQLiteDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("game_tools.Helpers.Equipments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllElementResistance")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmazingPower")
                        .HasColumnType("TEXT");

                    b.Property<string>("Armor")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttackSpeed")
                        .HasColumnType("TEXT");

                    b.Property<string>("CDR")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticalChance")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticalDamage")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticalHitChance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Damage")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageOverTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageSuppression")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncreasedDamageTaken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intelligence")
                        .HasColumnType("TEXT");

                    b.Property<short?>("ItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaximumHealth")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementSpeed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Needlevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceReduction")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialEffectDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialEffectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Strength")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskBatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Traded")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
